# Generated by Django 5.2.3 on 2025-10-23 16:09

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommend_api', '0017_album_album_name_trgm_gist_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='file_path',
        ),
        migrations.AddField(
            model_name='track',
            name='artists_text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='track',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddIndex(
            model_name='track',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='track_search_vector_gin'),
        ),
    ]
