# Generated by Django 5.2.3 on 2026-04-02 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommend_api', '0018_remove_track_file_path_track_artists_text_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='track',
            index=models.Index(fields=['-submissions', 'musicbrainz_recordingid'], name='track_subs_mbid_idx'),
        ),
    ]
