# Generated by Django 5.2.3 on 2026-04-21 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommend_api', '0019_track_track_subs_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='source_found_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='track',
            name='source_not_found_count',
            field=models.IntegerField(default=0),
        ),
    ]
