# Generated by Django 5.2.3 on 2026-04-27 11:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommend_api', '0020_track_source_found_count_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenreDortmund',
            fields=[
                ('code', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='GenreRosamerica',
            fields=[
                ('code', models.PositiveSmallIntegerField(primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=64, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='track',
            name='genre_dortmund',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='recommend_api.genredortmund'),
        ),
        migrations.AlterField(
            model_name='track',
            name='genre_rosamerica',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='recommend_api.genrerosamerica'),
        ),
    ]
