# Generated by Django 5.2.16 on 2026-09-26 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommend_api', '0021_genredortmund_genrerosamerica_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='track',
            name='source_found_count',
        ),
        migrations.RemoveField(
            model_name='track',
            name='source_not_found_count',
        ),
    ]
