# Generated by Django 5.2.16 on 2026-09-29 14:41

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models
from django.db.models import Q
from datetime import timedelta


def migrate_source_request_counts(apps, schema_editor):
    """
    Migrate source request counts from Track to TrackSource.

    The failure timestamp is intentionally expired so the next source request
    performs a fresh provider search instead of being blocked by the cooldown.
    """
    Track = apps.get_model('recommend_api', 'Track')
    TrackSource = apps.get_model('recommend_api', 'TrackSource')
    expired_failure_time = django.utils.timezone.now() - timedelta(days=2)

    tracks = (
        Track.objects.filter(
            Q(source_found_count__gt=0) | Q(source_not_found_count__gt=0)
        )
        .values_list(
            'pk',
            'source_found_count',
            'source_not_found_count',
        )
        .iterator()
    )

    sources = [
        TrackSource(
            track_id=pk,
            provider='youtube',
            source_request_count=found + not_found,
            last_lookup_failed_at=expired_failure_time,
        )
        for pk, found, not_found in tracks
    ]

    TrackSource.objects.bulk_create(sources, batch_size=1000)


class Migration(migrations.Migration):

    dependencies = [
        ('recommend_api', '0021_genredortmund_genrerosamerica_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_id', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('channel', models.CharField(blank=True, max_length=255, null=True)),
                ('thumbnail', models.URLField(blank=True, max_length=255, null=True)),
                ('url', models.URLField(blank=True, max_length=255, null=True)),
                ('provider', models.CharField(choices=[('youtube', 'YouTube')], default='youtube', max_length=15)),
                ('refreshed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('source_request_count', models.IntegerField(default=1)),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='recommend_api.track')),
                ('last_lookup_failed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'unique_together': {('track', 'provider')},
                'constraints': [models.CheckConstraint(condition=models.Q(('provider', 'youtube')), name='track_source_provider_youtube')],
            },
        ),
        migrations.RunPython(
            migrate_source_request_counts,
            migrations.RunPython.noop,
        ),
        migrations.RemoveField(
            model_name='track',
            name='source_found_count',
        ),
        migrations.RemoveField(
            model_name='track',
            name='source_not_found_count',
        ),
    ]
