# Generated by Django 5.2.16 on 2026-10-01 12:51

import django.contrib.postgres.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommend_api', '0022_remove_source_counts_and_create_track_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='isrc',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=12, validators=[django.core.validators.RegexValidator('^[A-Z]{2}[A-Z0-9]{3}[0-9]{7}$', 'The string is not a valid ISRC')]), blank=True, default=list, size=None),
        ),
    ]
