# Generated by Django 5.2.16 on 2026-09-29 11:59

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('recommend_api', '0023_tracksource'), ('recommend_api', '0024_alter_tracksource_refreshed_at'), ('recommend_api', '0025_tracksource_last_lookup_failed_at_and_more')]

    dependencies = [
        ('recommend_api', '0022_remove_track_source_found_count_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_id', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('channel', models.CharField(blank=True, max_length=255, null=True)),
                ('thumbnail', models.URLField(blank=True, max_length=255, null=True)),
                ('url', models.URLField(blank=True, max_length=255, null=True)),
                ('provider', models.CharField(choices=[('youtube', 'YouTube')], default='youtube', max_length=15)),
                ('refreshed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('source_request_count', models.IntegerField(default=1)),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='recommend_api.track')),
                ('last_lookup_failed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'unique_together': {('track', 'provider')},
                'constraints': [models.CheckConstraint(condition=models.Q(('provider', 'youtube')), name='track_source_provider_youtube')],
            },
        ),
    ]
