# Generated by Django 5.2.16 on 2026-09-26 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommend_api', '0022_remove_track_source_found_count_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_id', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('channel', models.CharField(max_length=255)),
                ('thumbnail', models.URLField(max_length=255)),
                ('url', models.URLField(max_length=255)),
                ('provider', models.CharField(choices=[('youtube', 'YouTube')], default='youtube', max_length=15)),
                ('refreshed_at', models.DateTimeField(auto_now=True)),
                ('source_request_count', models.IntegerField(default=1)),
                ('track', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recommend_api.track')),
            ],
            options={
                'unique_together': {('track', 'provider')},
                'constraints': [
                    models.CheckConstraint(
                        condition=models.Q(provider='youtube'),
                        name='track_source_provider_youtube',
                    ),
                ],
            },
        ),
    ]
