# Generated by Django 5.2.16 on 2026-09-28 13:07

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommend_api', '0023_tracksource'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tracksource',
            name='refreshed_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
