services:
  postgres:
    container_name: taste-mender-postgres
    image: postgres:18-alpine
    env_file:
      - .env
    environment:
      POSTGRES_DB: taste_mender_db
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql
    ports:
      - "127.0.0.1:5433:5432"
    restart: always

  django:
    container_name: taste-mender-web
    build:
      context: ..
      dockerfile: backend/Dockerfile
    ports:
      - "127.0.0.1:8000:8000"
    # Load environment variables from .env file (includes DATABASE_URL, POSTGRES_PASSWORD, API keys, etc)
    env_file:
      - .env
    # Override environment variables as needed
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/taste_mender_db
    depends_on:
      postgres:
        condition: service_started
    restart: unless-stopped

volumes:
  postgres_data: